# **LAB 3: PyTorch Fundamental**


## **OBJECTIVE**
To understand the basic concepts of PyTorch, tensor creation, tensor operations, data types, shapes, and device management.



## **THEORY**

### Introduction to PyTorch
PyTorch is an open-source deep learning framework developed by Meta AI. It provides a flexible and efficient environment for numerical computation and machine learning. Unlike traditional numerical libraries, PyTorch supports automatic differentiation, making it suitable for training neural networks.

### Why Use PyTorch?
- Dynamic computation graphs
- GPU acceleration support
- Easy debugging and experimentation
- Extensive ecosystem for deep learning and research

### Tensors in PyTorch
A tensor is a multi-dimensional array used to store and manipulate data. Tensors are similar to NumPy arrays but can run on GPUs for faster computation.

### **3.1. Tensor Dimensions**
- **Scalar (0-D Tensor):** A single number, such as 5 or -3.14.
- **Vector (1-D Tensor):** A one-dimensional array, such as [1, 2, 3, 4].
- **Matrix (2-D Tensor):** A two-dimensional array, like a table with rows and columns: [[1, 2], [3, 4]].
- **Tensor (N-D Tensor):** The generalized algebraic framework for multi-dimensional numerical arrays of an arbitrary number of axes (N>3). Tensors handle complex, high-dimensional structures natively, such as color images.

In [50]:
import torch
print("PyTorch Version:", torch.__version__)

PyTorch Version: 2.12.0


### **3.1.1. Scalar**

Scalars are used to represent quantities such as loss values, temperatures, or single numerical measurements.

In [51]:
# creating scalar using tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [52]:
print(scalar.ndim)
print(scalar.item()) #only works with one-element tensors
print(scalar.shape)

0
7
torch.Size([])


### **3.1.2. Vectors**

Vectors are commonly used to represent features, coordinates, and sequences of numerical data.

In [53]:
# vector
vector = torch.tensor([7, 8, 9, 10])
vector

tensor([ 7,  8,  9, 10])

In [54]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([4])


### **3.1.3. Matrix**

Matrices are extensively used in machine learning for storing datasets, performing transformations, and representing weights in neural networks.

In [55]:
# Matrix
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [56]:
print(matrix.ndim)
print(matrix.shape)

2
torch.Size([3, 3])


### **3.1.4. Tensor**

- A tensor is a generalized form of scalars, vectors, and matrices. 
- Tensors can have multiple dimensions and are used to represent complex data such as images, videos, and batches of training samples.

In [57]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [58]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


#### **3.1.4.1. Random Tensors**

Random tensors contain randomly generated values and are widely used for weight initialization, testing algorithms, generating sample data, and simulating inputs during model development.

In [59]:
# randomize tensors
# Create a random tensor of size (2, 3)
random_tensor = torch.rand(size=(2, 3))
random_tensor, random_tensor.dtype

(tensor([[0.0319, 0.4367, 0.0667],
         [0.6708, 0.6198, 0.2379]]),
 torch.float32)

In [60]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#### **3.1.4.2. Tensors of only Zeros and Ones** 

- Zero and one tensors are useful for initialization, masking operations, padding, and creating reference structures. 
- They are commonly used when preparing data for machine learning tasks.

In [61]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [62]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

#### **3.1.4.3. Creating a range and tensors like**

PyTorch provides functions to generate tensors containing sequential values or tensors with the same shape as existing tensors. 
- These functions simplify tensor creation and data preparation.

In [63]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### **3.1.4.4. Tensor datatypes**

- PyTorch supports multiple tensor data types for storing numerical data.
- The default data type is torch.float32, commonly used in deep learning.
- Floating-point data types include:
  - torch.float16 (16-bit)
  - torch.float32 (32-bit)
  - torch.float64 (64-bit)
- Integer data types are available in 8-bit, 16-bit, 32-bit, and 64-bit formats.
- Integer types store whole numbers, while floating-point types can store decimal values.
- Different data types provide different levels of precision and memory usage.
- Higher precision offers better numerical accuracy but requires more memory and computation.
- Lower precision reduces memory consumption and increases computational speed.
- Choosing an appropriate data type helps balance performance and accuracy in machine learning applications.

In [65]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([2.0, 4.0, 6.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [66]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

## 3.2. Getting information from tensors

The three of the most common attributes you'll want to find out about tensors are:

- `shape` - what shape is the tensor? (some operations require specific shape rules)
- `dtype` - what datatype are the elements within the tensor stored in?
- `device` - what device is the tensor stored on? (usually GPU or CPU)

In [67]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.4443, 0.2485, 0.6252, 0.7534],
        [0.5823, 0.0054, 0.2290, 0.5571],
        [0.1115, 0.7817, 0.4556, 0.1987]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## **3.3. Tensor Operations**

Tensor operations include arithmetic operations, matrix multiplication, aggregation, reshaping, and broadcasting. These operations form the foundation of deep learning computations and numerical processing in PyTorch.

In deep learning, different types of data such as images, text, audio, videos, and other information are converted into **tensors** (multi-dimensional arrays of numbers).

A model learns by repeatedly performing mathematical operations on these tensors to discover patterns and relationships in the data. During training, millions of calculations may be carried out.

Some of the most common tensor operations include:

- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

By combining these operations, (neural) networks/models can learn useful representations of data and make predictions.

In [68]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [69]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [70]:
tensor

tensor([1, 2, 3])

In [71]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [72]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([-90, -80, -70])

In [73]:
tensor

tensor([-9, -8, -7])

In [74]:
tensor = tensor + 10
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)
print("Equals:", torch.multiply(tensor, tensor))

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
Equals: tensor([1, 4, 9])


In [75]:
# Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.
tensor = torch.tensor([1, 2, 3])

# Element-wise matrix multiplication
print(tensor * tensor)

# Matrix multiplication
print(torch.matmul(tensor, tensor))

tensor([1, 4, 9])
tensor(14)


In [76]:
tensor_A = torch.tensor([[1, 2, 3],
                         [4, 5, 6]])

tensor_B = torch.tensor([[7, 8, 9],
                         [10, 11, 12]])

# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")

output = torch.matmul(tensor_A, tensor_B.T)

print("Output:\n")
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([2, 3]), tensor_B = torch.Size([2, 3])

New shapes: tensor_A = torch.Size([2, 3]) (same as above), tensor_B.T = torch.Size([3, 2])

Multiplying: torch.Size([2, 3]) * torch.Size([3, 2]) <- inner dimensions match

Output:

tensor([[ 50,  68],
        [122, 167]])

Output shape: torch.Size([2, 2])


#### **Finding the min, max, mean, sum, etc (aggregation)**

In [77]:
x = torch.arange(0, 100, 10)
print(x)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


#### **Positional min/max**


In [78]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


**Change tensor datatype**

In [79]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
print(tensor.dtype)

# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

torch.float32


tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

#### **Reshaping**

- `torch.reshape(input, shape)`:	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().

In [80]:
# Create a tensor
import torch
x = torch.arange(1., 9.)
print(x, x.shape)

# Add an extra dimension
x_reshaped = x.reshape(1, 8) # try other shapes, it will produce an error.
x_reshaped, x_reshaped.shape

tensor([1., 2., 3., 4., 5., 6., 7., 8.]) torch.Size([8])


(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

#### **View**

- `Tensor.view(shape)`:	Returns a view of the original tensor in a different shape but shares the same data as the original tensor.

In [81]:
# Change view (keeps same data as original but changes view)
z = x.view(1, 8)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [82]:
z = x.view(2,4)
z, z.shape

(tensor([[1., 2., 3., 4.],
         [5., 6., 7., 8.]]),
 torch.Size([2, 4]))

In [83]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [84]:
import torch
x = torch.arange(6)
# print(x,x.shape)

a = x.view(2, 3)
b = x.reshape(2, 3)

a[0, 0] = 100
print(x)

tensor([100,   1,   2,   3,   4,   5])


#### **Stack**

- `torch.stack(tensors, dim=0)`:	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.

In [85]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) 
x_stacked

tensor([[100,   1,   2,   3,   4,   5],
        [100,   1,   2,   3,   4,   5],
        [100,   1,   2,   3,   4,   5],
        [100,   1,   2,   3,   4,   5]])

In [86]:
# Stacking using dim=1
x_stacked = torch.stack([x, x, x, x], dim=1) 
x_stacked

tensor([[100, 100, 100, 100],
        [  1,   1,   1,   1],
        [  2,   2,   2,   2],
        [  3,   3,   3,   3],
        [  4,   4,   4,   4],
        [  5,   5,   5,   5]])

#### **Squeeze and Unsqueeze funtions.**

In [87]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])
Previous shape: torch.Size([1, 8])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8.])
New shape: torch.Size([8])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])
New shape: torch.Size([1, 8])


#### **Permute**

- `torch.permute()` is used to rearrange the order of a tensor's dimensions (axes) without changing the underlying data values.

In [88]:
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(x.shape)

y = x.permute(1, 0)

print(y)
print(y.shape)

torch.Size([2, 3])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([3, 2])


## 3.4. Indexing


- Indexing allows access to specific elements, rows, columns, or slices of a tensor. 
- It is useful for data extraction, manipulation, filtering, and selecting subsets of information from large datasets.

In [89]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [90]:
print(x[:, 0]) # Get all values of 0th dimension and the 0 index of 1st dimension
print(x[:, :, 1])# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
print(x[:, 1, 1]) # Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
print(x[0, 0, :]) # same as x[0][0]

tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([5])
tensor([1, 2, 3])


## 3.5. Pytorch Tensor to NumPy arrays and vice versa

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

- `torch.from_numpy(ndarray)` - NumPy array -> PyTorch tensor.
- `torch.Tensor.numpy()` - PyTorch tensor -> NumPy array.

In [91]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [92]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## 3.6. Tensors on GPU

- GPUs provide parallel processing capabilities that significantly accelerate tensor computations. 
- PyTorch allows tensors to be moved between CPU and GPU devices, enabling faster training and inference for deep learning models.

In [93]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


In [94]:
# Check for GPU
import torch
torch.cuda.is_available()

False

In [95]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [96]:
# Count number of devices
torch.cuda.device_count()

0

In [97]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

In [98]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## **DISCUSSION**

In this particular laboratory exercise, we had a chance to learn the basics of PyTorch tensors and their application. Among the things that we learned was how to create and manipulate various types of tensors, which range from scalars, vectors, matrices, and more complex tensor types. The operations involved in these exercises included mathematical operations on the tensors, as well as accessing tensor elements through indexing. Furthermore, we got acquainted with GPU computing and saw first-hand how the graphics processing unit is used by PyTorch in performing various tasks.

## **CONCLUSION**

The objectives of learning about PyTorch tensors were fully achieved through this laboratory exercise. By working with tensors, manipulating them, and carrying out various operations on them, we got to know how data is handled in PyTorch. It was also possible to learn more about tensor indexing, data type, interoperability with NumPy, and GPU computing. What we have learned here provides a solid foundation for the next stage of our machine learning journey.